### PR TITLE
Proposing USI format changes

### PR DESCRIPTION
**Pull request by mwang87**
Proposes a format change for Metabolomics USI identifiers that will be sychronized with this PR:

https://github.com/mwang87/MetabolomicsSpectrumResolver/pull/88

### CODE REVIEW

**Comment by mwang87** [comment]
updates for USI, ready to be reviewed.

**Comment by tsufz** [comment]
Hi @mwang87, @meier-rene will review the code soon. However, could you use the dev branch to submit code to MassBank? The master is used for stable revisions only.

Best,
Tobias

**Comment by mwang87** [comment]
Definitely! Thanks so much Tobias!

**Comment by meier-rene** [comment]
Thank you for your notification of the change. I have included your changes in ee1d079 and will release a new version very soon, so that the changes get online.

**Pull request closed without merging**
