### PR TITLE
Update record format

### PR DESCRIPTION
**Pull request by tsufz**
Updata records format and bump to version 2.4.

### CODE REVIEW

**Comment by schymane** [comment]
I received an email earlier today with additional field suggestions. They want to add precursor intensity and concentration of the chemical. Do you want to hold off with revising until they have replied? For the record I suggested AC$CONCENTRATION and MS$FOCUSED_ION: PRECURSOR_INT.
I mentioned we were revising it like right now ...

**Comment by tsufz** [comment]
In meanwhile some comments came in...

**Comment by tsufz** [comment]
@schymane, do you know when they will details on their invention? I would like to release 2.4 soon to get it from the table and to start the work with implementation.

**Comment by meier-rene** [comment]
Would "AC$CHROMATOGRAPHY CONCENTRATION"  fit?

**Comment by schymane** [comment]
I toyed with a few ideas and kept landing on AC$CONCENTRATION

We do not always have chromatography (direct infusion?)
MS$FOCUSED_ION CONCENTRATION is also an alternative but certainly not ideal because this has already been ionised. 
CH$ also inappropriate as it's the chemical information not the concentration (which is an analytical condition ... hence AC is the proper home in my opinion...)

**Comment by tsufz** [comment]
I added the AC$GENERAL section 2.4.7 for such purposes.

**Comment by sneumann** [comment]
Hm. In all publications with analytical chemistry I totally support reporting concentrations. 
In our case, what's the difference in a MS/MS spectrum of 0.001 mol/l caffeine solution 
vs. an MS/MS of  10.0 mol/l caffeine ? What was the intended use case ? Ionisation efficiency ? 
I am hesitant to add too much detail. Similarly, what is the intention behind precursor intensity ? 
The Grant lab at UConn looked into that (Ecom50). Would we have enough information if we did target those use cases ? I suggest that if we add information, we also give examples in the docs what this can be actually used for. Yours, Steffen

**Comment by schymane** [comment]
The email contact wanted indeed to use this data to predict ionisation efficiency based on information such as concentration and precursor intensity. All other info needed is already available (if provided) in the record format. I understand the unwillingness to add too much detail and these should certainly not be compulsory fields, however this is information that people may have. I am not sure how many people will actually add this information and I would be hesitant to add it to RMB esp with our lack of active programmers on it right now, but I see no harm to add it to the record format to standardize it if people wish to add it (otherwise it will e.g. end up in the COMMENT field...)?

**Pull request closed without merging**
